repos:
- repo: local
  hooks:
  - id: flake8
    name: Flake8
    description: This hook runs flake8 within our project's pipenv environment.
    entry: pipenv run lint
    language: python
    types: [python]
    require_serial: true
  - id: pytest
    name: PyTest
    description: This hook runs tests within project's environment.
    entry: pipenv run test
    language: python
    types: [python]
    require_serial: true
