exclude: 
default_language_version:
    # force all unspecified python hooks to run python3
    python: python3
default_stages:
  - commit

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.1.0
  hooks:
  # Python Checks
  - id: check-ast
  - id: debug-statements
  - id: name-tests-test
  - id: flake8
  # Config Hooks
  - id: check-json
  - id: check-xml
  - id: check-yaml
  # General Hooks
  - id: trailing-whitespace
  - id: end-of-file-fixer
  # Git related hooks
  - id: check-merge-conflict
  - id: no-commit-to-branch
    args:
      - "--branch=dev"
      - "--branch=master"
- repo: git://github.com/PyCQA/pydocstyle
  rev: master
  hooks:
    - id: pydocstyle
- repo: https://github.com/asottile/reorder_python_imports
  rev: v1.2.0
  hooks:
    - id: reorder-python-imports
