name: Lint and test

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        cd brilliant-builders
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv sync 
    - name: Lint 
      run: |
        cd brilliant-builders
        pipenv run lint
    - name: Test 
      run: |
        cd brilliant-builders
        pipenv run test
